openapi: 3.0.3
info:
  title: STD23109 - TD1 API
  version: 1.0.0
  contact:
    name: API Support
    email: support@std230109.com
  license:
    name: MIT License

servers:
  - url: https://localhost.std230109.com

paths:
  /customers:
    get:
      summary: Retrieve a list of customers
      tags:
        - customer
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

    post:
      summary: Create new customers
      tags:
        - customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/CreateCustomer"
      responses:
        "201":
          description: Customers created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

    put:
      tags:
        - customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        "200":
          description: Customer updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"

    delete:
      summary: Delete customers
      tags:
        - customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                description: Customer ID
      responses:
        "200":
          description: Customers deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer

    CreateCustomer:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
