openapi: 3.0.3
info:
  title: STD23109 - TD2 API
  version: 1.0.1
  contact:
    name: API Support
    email: support@std230109.com
  license:
    name: MIT License

servers:
  - url: https://localhost.std230109.com

paths:
  /meals:
    get:
      summary: Retrieve a list of meals
      tags:
        - meal
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: List of meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Meal"

    post:
      summary: Create new meals
      tags:
        - meal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/CreateMeal"
      responses:
        "201":
          description: Meals created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Meal"

    put:
      summary: Update existing meals
      tags:
        - meal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Meal"
      responses:
        "200":
          description: Meal updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Meal"

    delete:
      summary: Delete meals
      tags:
        - meal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                description: Meal ID
      responses:
        "200":
          description: Meals deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Meal"

components:
  schemas:
    Meal:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
          format: float

    CreateMeal:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
          format: float
